create table if not exists cls_product
(
    id                    integer generated by default as identity not null
        constraint cls_product_pkey
            primary key,
    name                  text,
    limitation            integer,
    min_amount_w_deposit  integer,
    max_amount_w_deposit  integer,
    min_amount_wo_deposit integer,
    max_amount_wo_deposit integer,
    interest_rate         float,
    has_key_rate          boolean,
    is_deleted            boolean,
    is_hidden             boolean,
    time_create           timestamp default CURRENT_TIMESTAMP      not null
);